### ISSUE TITLE
Календарь на 2025 год

### ISSUE THREAD

**Issue by GVCoder09** [AlexandrKozlovskiy/OrthodoxCalendar#3]
Добрый день! Пользуюсь вашей разработкой уже больше 5 лет, очень нравится. Скажите, пожалуйста, будет ли календарь на 2025 год? Уже середина декабря и обновления всё нет и нет. Планируется ли продолжение проекта?

**Comment by AlexandrKozlovskiy** [comment]
Да,календарь будет,но,возможно,не весь сразу,хотя в течении года он будет дополняться.

**Comment by GVCoder09** [comment]
> Да,календарь будет,но,возможно,не весь сразу,хотя в течении года он будет дополняться.

Спасибо за ваш труд!

**Comment by AlexandrKozlovskiy** [comment]
Пусть будет во славу Божью. Кстати все вы можете отправлять нам пулл реквесты по улучшению нашего приложения.
